apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
spec:
  containers:
  # This is the image containing the (somewhat) broken app.
  - image: luksa/kubia-unhealthy
    name: kubia
    # A liveness probe that will perform an HTTP GET
    livenessProbe:
      httpGet:
        # The path to request in the HTTP request
        path: /
        # The network port HTTP request the probe should connect to
        port: 8080

