apiVersion: v1
kind: Pod
metadata:
  name: mongodb-aws
spec:
  volumes:
  - name: mongodb-data
    # Using awsElasticBlockStore instead of gcePersistentDisk
    awsElasticBlockStore:
      # Specify the ID of the EBS volume you created.
      volumeID: my-volume
      # The filesystem type is EXT4 as before.
      fsType: ext4
  containers:
  - image: mongo
    name: mongodb
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
    ports:
    - containerPort: 27017
      protocol: TCP

