apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc2 
# You’re not specifying the storageClassName attribute (unlike earlier examples).
spec:
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
