apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
# The volume plugin to use for provisioning the PersistentVolume
provisioner: kubernetes.io/gce-pd
parameters:
  # The parameters passed to the provisioner
  type: pd-ssd
  zone: europe-west1-b
