apiVersion: v1
kind: Pod
metadata:
  name: gitrepo-volume-gitsync-pod
spec:
  volumes:
  - name: git-sync-volume
    emptyDir: {}

  containers:
  - name: git-sync
    image: jlowin/git-sync
    volumeMounts:
    - name: git-sync-volume
      mountPath: /git
    env:
    - name: GIT_SYNC_REPO
      value: "https://github.com/minasys/kubia-website-example.git"
    - name: GIT_SYNC_DEST
      value: /git
      # the sync wait value is in seconds
    - name: GIT_SYNC_WAIT
      value: "1"

  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: git-sync-volume
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
