apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc 
spec:
  # Specifying an empty string as the storage class name ensures the PVC binds to a pre-provisioned PV 
  # instead of dynamically provisioning a new one.
  storageClassName: ""
  #resources:
    #requests:
      #storage: 100Mi
  #accessModes:
    #- ReadWriteOnce
