# Specifying capabilities in a PodSecurityPolicy
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: default
spec:
  # Allow containers to add the SYS_TIME capability.
  allowedCapabilities:
  - SYS_TIME
  # Automatically add the CHOWN capability to every container.
  defaultAddCapabilities:
  - CHOWN
  # Require containers to drop the SYS_ADMIN and SYS_MODULE capabilities.
  requiredDropCapabilities:
  - SYS_ADMIN
  - SYS_MODULE
  hostIPC: false
  hostPID: false
  hostNetwork: false
  hostPorts:
  - min: 10000
    max: 11000
  - min: 13000
    max: 14000
  privileged: false
  readOnlyRootFilesystem: true
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  volumes:
  - '*'
