apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test
  namespace: foo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  # This RoleBinding references the service-reader Role.
  kind: Role
  name: service-reader
subjects: 
# And binds it to the default ServiceAccount in the foo namespace.
- kind: ServiceAccount
  name: default
  namespace: foo
