apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pv-test
  namespace: foo
roleRef:
  # Although you can create a RoleBinding and have it reference a ClusterRole when you
  # want to enable access to namespaced resources, you can’t use the same approach for
  # cluster-level (non-namespaced) resources. To grant access to cluster-level resources,
  # you must always use a ClusterRoleBinding.
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pv-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: foo
