# A ClusterRole definition
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # ClusterRoles aren’t namespaced, hence no namespace field.
  name: pv-reader
rules:
# In this case, the rules are exactly like those in a regular Role.
- apiGroups: [""]
  verbs: ["get", "list"]
  resources: ["persistentvolumes"]

