apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kubia
spec:
# Two properties affect how many pods are replaced at once during a Deployment’s rolling
# update. They are maxSurge and maxUnavailable and can be set as part of the
# rollingUpdate sub-property of the Deployment’s strategy attribute
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  replicas: 3
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
      - image: luksa/kubia:v1
        name: nodejs
