apiVersion: v1
kind: Pod
metadata:
  name: fortune-env-from-configmap
spec:
  containers:
  - image: luksa/fortune:env
  # Using envFrom instead of env to pass all all entries of a ConfigMap as environment variables at once
    envFrom:
    # All environment variables will be prefixed with CONFIG_
    - prefix: CONFIG_
        configMapKeyRef:
          name: fortune-config
    name: html-generator
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: html
    emptyDir: {}
