# A container with a read-only filesystem
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-readonly-filesystem
spec:
  containers:
  - name: main
    image: alpine
    command: ["/bin/sleep", "999999"]
    # This container’s filesystem can’t be written to...
    securityContext:
      readOnlyRootFilesystem: true
    # ...but writing to /volume is allowed, becase a volume is mounted there.
    volumeMounts:
    - name: my-volume
      mountPath: /volume
      readOnly: false
  volumes:
  - name: my-volume
    emptyDir:
