apiVersion: v1
kind: Service
metadata:
  # Name of the Service
  name: kubia
spec:
  # The StatefulSet’s governing Service must be headless. It will enable peer discovery between your pods
  clusterIP: None
  # All pods with the app=kubia label belong to this service.
  selector:
    app: kubia
  ports:
  - name: http
    port: 80
