apiVersion: v1
kind: Pod
metadata:
  name: kubia-gpu
spec:
  # nodeSelector tells Kubernetes to deploy this pod only to nodes containing the gpu=true label.
  nodeSelector:
    gpu: "true"
  containers:
  - image: luksa/kubia
    name: kubia
